title: Deepen Kumar Sahoo
logo: /assets/img/Deepen.jpeg



description:
  <p>
  <br>   
  I'm learning Machine Learning and Artificial Intelligence.
  I have enrolled in Executive PG Program in AI ML.
  I'm a student of IIIT Bangalore.
  I have 4+ years of working experience in client-facing roles.
  I am looking for opportunities in AI/ML.
  <br>
  </p>



theme: jekyll-theme-minimal
